apiVersion: v1
kind: Service
metadata:
  name: alphapt-app-service
  namespace: alphapt-production
  labels:
    app: alphapt
    component: trading-engine
spec:
  selector:
    app: alphapt
    component: trading-engine
  ports:
  - name: api
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: websocket
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alphapt-api-service
  namespace: alphapt-production
  labels:
    app: alphapt
    component: api-server
spec:
  selector:
    app: alphapt
    component: api-server
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: websocket
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: alphapt-metrics
  namespace: alphapt-production
  labels:
    app: alphapt
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: alphapt
    component: trading-engine
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP