# Mean Reversion Strategy Configuration
strategy_name: 'MeanReversion_NIFTY_1'
strategy_class: 'MeanReversionStrategy'
module_name: 'strategies.mean_reversion'
instrument_tokens: [256265]  # NIFTY 50 only
parameters:
  window_size: 20
  entry_threshold: 2.0  # Standard deviations
  exit_threshold: 0.5
  max_position_size: 50
  max_drawdown_percent: 0.15
  max_history: 100
brokers: ['paper']  # Paper trading only initially
enabled: true