strategy_name: 'NIFTY RSI Strategy'
strategy_class: 'rsi'  # Simple RSI strategy
enabled: true
parameters:
  rsi_period: 14
  rsi_oversold: 30
  rsi_overbought: 70
  position_size: 100
brokers: ['paper']
instruments: [256265]  # NIFTY 50 token

# Optional configuration
description: 'Pure RSI strategy for momentum trading'
tags: ['rsi', 'rules-based', 'momentum', 'simple']
risk_limits:
  max_position_size: 10000.0
  risk_multiplier: 1.0